import type { Formula } from '../types';

export const formulas: Formula[] = [
  // Chapter 2: Financial Statements and Cash Flow
  {
    id: 'ch2-income',
    name: 'Income Statement Equation',
    category: 'Financial Statements',
    chapter: 2,
    formula: 'Income = Revenue - Expenses',
    latex: '\\text{Income} = \\text{Revenue} - \\text{Expenses}',
    variables: [
      { symbol: 'Revenue', name: 'Revenue', description: 'Total operating revenues from principal operations' },
      { symbol: 'Expenses', name: 'Expenses', description: 'All costs including COGS, operating expenses, depreciation, interest, and taxes' },
      { symbol: 'Income', name: 'Net Income', description: 'The bottom line profit after all expenses' }
    ],
    description: 'The fundamental accounting definition of income',
    difficulty: 'basic',
    tags: ['income-statement', 'accounting', 'fundamentals']
  },
  {
    id: 'ch2-nwc',
    name: 'Net Working Capital',
    category: 'Financial Statements',
    chapter: 2,
    formula: 'NWC = Current Assets - Current Liabilities',
    latex: '\\text{NWC} = \\text{Current Assets} - \\text{Current Liabilities}',
    variables: [
      { symbol: 'NWC', name: 'Net Working Capital', description: 'Short-term liquidity measure' },
      { symbol: 'Current Assets', name: 'Current Assets', description: 'Assets that can be converted to cash within one year' },
      { symbol: 'Current Liabilities', name: 'Current Liabilities', description: 'Liabilities due within one year' }
    ],
    description: 'Measures the firm\'s short-term liquidity and operating efficiency',
    difficulty: 'basic',
    tags: ['balance-sheet', 'liquidity', 'working-capital']
  },
  {
    id: 'ch2-ocf',
    name: 'Operating Cash Flow',
    category: 'Cash Flow',
    chapter: 2,
    formula: 'OCF = EBIT + Depreciation - Taxes',
    latex: '\\text{OCF} = \\text{EBIT} + \\text{Depreciation} - \\text{Taxes}',
    variables: [
      { symbol: 'OCF', name: 'Operating Cash Flow', description: 'Cash generated from operations' },
      { symbol: 'EBIT', name: 'Earnings Before Interest and Taxes', description: 'Operating income before financing costs' },
      { symbol: 'Depreciation', name: 'Depreciation', description: 'Non-cash expense added back to cash flow' },
      { symbol: 'Taxes', name: 'Current Taxes', description: 'Current tax payments (not deferred)' }
    ],
    description: 'Calculates the actual cash generated by the firm\'s operations',
    example: {
      problem: 'Calculate OCF if EBIT = $159M, Depreciation = $90M, Current Taxes = $15M',
      solution: 'OCF = $159 + $90 - $15 = $234 million',
      values: { EBIT: 159, Depreciation: 90, Taxes: 15, OCF: 234 }
    },
    difficulty: 'intermediate',
    tags: ['cash-flow', 'operations', 'financial-analysis']
  },
  {
    id: 'ch2-cf-firm',
    name: 'Cash Flow of the Firm',
    category: 'Cash Flow',
    chapter: 2,
    formula: 'CF(A) = CF(B) + CF(S)',
    latex: '\\text{CF}(\\text{Assets}) = \\text{CF}(\\text{Bondholders}) + \\text{CF}(\\text{Stockholders})',
    variables: [
      { symbol: 'CF(A)', name: 'Cash Flow to Assets', description: 'Total cash generated by firm assets' },
      { symbol: 'CF(B)', name: 'Cash Flow to Bondholders', description: 'Cash paid to creditors (interest + debt retirement - new debt)' },
      { symbol: 'CF(S)', name: 'Cash Flow to Stockholders', description: 'Cash paid to shareholders (dividends + repurchases - new equity)' }
    ],
    description: 'Fundamental principle: cash from assets must equal cash to investors',
    difficulty: 'intermediate',
    tags: ['cash-flow', 'corporate-finance', 'fundamental']
  },

  // Chapter 3: Financial Statement Analysis
  {
    id: 'ch3-current-ratio',
    name: 'Current Ratio',
    category: 'Liquidity Ratios',
    chapter: 3,
    formula: 'Current Ratio = Current Assets / Current Liabilities',
    latex: '\\text{Current Ratio} = \\frac{\\text{Current Assets}}{\\text{Current Liabilities}}',
    variables: [
      { symbol: 'Current Assets', name: 'Current Assets', description: 'Assets convertible to cash within one year' },
      { symbol: 'Current Liabilities', name: 'Current Liabilities', description: 'Liabilities due within one year' }
    ],
    description: 'Measures ability to pay short-term obligations with short-term assets',
    difficulty: 'basic',
    tags: ['ratio-analysis', 'liquidity', 'solvency']
  },
  {
    id: 'ch3-quick-ratio',
    name: 'Quick Ratio (Acid-Test)',
    category: 'Liquidity Ratios',
    chapter: 3,
    formula: 'Quick Ratio = (Current Assets - Inventory) / Current Liabilities',
    latex: '\\text{Quick Ratio} = \\frac{\\text{Current Assets} - \\text{Inventory}}{\\text{Current Liabilities}}',
    variables: [
      { symbol: 'Current Assets', name: 'Current Assets', description: 'Short-term assets' },
      { symbol: 'Inventory', name: 'Inventory', description: 'Least liquid current asset, excluded from quick ratio' },
      { symbol: 'Current Liabilities', name: 'Current Liabilities', description: 'Short-term obligations' }
    ],
    description: 'Stricter liquidity measure excluding inventory',
    difficulty: 'basic',
    tags: ['ratio-analysis', 'liquidity', 'acid-test']
  },
  {
    id: 'ch3-debt-equity',
    name: 'Debt-Equity Ratio',
    category: 'Leverage Ratios',
    chapter: 3,
    formula: 'D/E Ratio = Total Debt / Total Equity',
    latex: '\\text{D/E} = \\frac{\\text{Total Debt}}{\\text{Total Equity}}',
    variables: [
      { symbol: 'Total Debt', name: 'Total Debt', description: 'Sum of short-term and long-term debt' },
      { symbol: 'Total Equity', name: 'Total Equity', description: 'Shareholders\' equity' }
    ],
    description: 'Measures financial leverage and capital structure',
    difficulty: 'basic',
    tags: ['ratio-analysis', 'leverage', 'capital-structure']
  },
  {
    id: 'ch3-equity-multiplier',
    name: 'Equity Multiplier',
    category: 'Leverage Ratios',
    chapter: 3,
    formula: 'Equity Multiplier = Total Assets / Total Equity = 1 + D/E',
    latex: '\\text{EM} = \\frac{\\text{Total Assets}}{\\text{Total Equity}} = 1 + \\text{D/E}',
    variables: [
      { symbol: 'Total Assets', name: 'Total Assets', description: 'All assets owned by the firm' },
      { symbol: 'Total Equity', name: 'Total Equity', description: 'Shareholders\' equity' },
      { symbol: 'D/E', name: 'Debt-Equity Ratio', description: 'Financial leverage ratio' }
    ],
    description: 'Alternative measure of financial leverage used in DuPont Identity',
    difficulty: 'intermediate',
    tags: ['ratio-analysis', 'leverage', 'dupont']
  },
  {
    id: 'ch3-tat',
    name: 'Total Asset Turnover',
    category: 'Efficiency Ratios',
    chapter: 3,
    formula: 'TAT = Sales / Total Assets',
    latex: '\\text{TAT} = \\frac{\\text{Sales}}{\\text{Total Assets}}',
    variables: [
      { symbol: 'Sales', name: 'Sales', description: 'Total revenue' },
      { symbol: 'Total Assets', name: 'Total Assets', description: 'All assets' }
    ],
    description: 'Measures efficiency of asset utilization in generating sales',
    example: {
      problem: 'Sales = $2,311M, Total Assets = $3,588M. Calculate TAT.',
      solution: 'TAT = $2,311 / $3,588 = 0.64 times',
      values: { Sales: 2311, 'Total Assets': 3588, TAT: 0.64 }
    },
    difficulty: 'basic',
    tags: ['ratio-analysis', 'efficiency', 'turnover']
  },
  {
    id: 'ch3-inventory-turnover',
    name: 'Inventory Turnover',
    category: 'Efficiency Ratios',
    chapter: 3,
    formula: 'Inventory Turnover = COGS / Inventory',
    latex: '\\text{Inventory Turnover} = \\frac{\\text{COGS}}{\\text{Inventory}}',
    variables: [
      { symbol: 'COGS', name: 'Cost of Goods Sold', description: 'Direct costs of producing goods sold' },
      { symbol: 'Inventory', name: 'Inventory', description: 'Average inventory level' }
    ],
    description: 'Measures how quickly inventory is sold',
    difficulty: 'basic',
    tags: ['ratio-analysis', 'efficiency', 'inventory']
  },
  {
    id: 'ch3-days-sales',
    name: 'Days Sales in Inventory',
    category: 'Efficiency Ratios',
    chapter: 3,
    formula: 'Days Sales in Inventory = 365 / Inventory Turnover',
    latex: '\\text{Days Sales in Inventory} = \\frac{365}{\\text{Inventory Turnover}}',
    variables: [
      { symbol: 'Inventory Turnover', name: 'Inventory Turnover', description: 'Number of times inventory is sold per year' }
    ],
    description: 'Average number of days inventory is held before being sold',
    difficulty: 'basic',
    tags: ['ratio-analysis', 'efficiency', 'inventory']
  },
  {
    id: 'ch3-receivables-turnover',
    name: 'Receivables Turnover',
    category: 'Efficiency Ratios',
    chapter: 3,
    formula: 'Receivables Turnover = Sales / Accounts Receivable',
    latex: '\\text{Receivables Turnover} = \\frac{\\text{Sales}}{\\text{Accounts Receivable}}',
    variables: [
      { symbol: 'Sales', name: 'Sales', description: 'Total revenue' },
      { symbol: 'Accounts Receivable', name: 'Accounts Receivable', description: 'Money owed by customers' }
    ],
    description: 'Measures how quickly receivables are collected',
    difficulty: 'basic',
    tags: ['ratio-analysis', 'efficiency', 'receivables']
  },
  {
    id: 'ch3-profit-margin',
    name: 'Profit Margin',
    category: 'Profitability Ratios',
    chapter: 3,
    formula: 'Profit Margin = Net Income / Sales',
    latex: '\\text{PM} = \\frac{\\text{Net Income}}{\\text{Sales}}',
    variables: [
      { symbol: 'Net Income', name: 'Net Income', description: 'Bottom line profit' },
      { symbol: 'Sales', name: 'Sales', description: 'Total revenue' }
    ],
    description: 'Measures operating efficiency - how much profit per dollar of sales',
    difficulty: 'basic',
    tags: ['ratio-analysis', 'profitability', 'margins']
  },
  {
    id: 'ch3-roa',
    name: 'Return on Assets',
    category: 'Profitability Ratios',
    chapter: 3,
    formula: 'ROA = Net Income / Total Assets',
    latex: '\\text{ROA} = \\frac{\\text{Net Income}}{\\text{Total Assets}}',
    variables: [
      { symbol: 'Net Income', name: 'Net Income', description: 'Bottom line profit' },
      { symbol: 'Total Assets', name: 'Total Assets', description: 'All assets' }
    ],
    description: 'Measures how efficiently assets generate profit',
    difficulty: 'basic',
    tags: ['ratio-analysis', 'profitability', 'returns']
  },
  {
    id: 'ch3-roe',
    name: 'Return on Equity',
    category: 'Profitability Ratios',
    chapter: 3,
    formula: 'ROE = Net Income / Total Equity',
    latex: '\\text{ROE} = \\frac{\\text{Net Income}}{\\text{Total Equity}}',
    variables: [
      { symbol: 'Net Income', name: 'Net Income', description: 'Bottom line profit' },
      { symbol: 'Total Equity', name: 'Total Equity', description: 'Shareholders\' equity' }
    ],
    description: 'Measures return to shareholders - the key performance metric',
    difficulty: 'basic',
    tags: ['ratio-analysis', 'profitability', 'returns', 'dupont']
  },
  {
    id: 'ch3-dupont-3',
    name: 'DuPont Identity (3-part)',
    category: 'DuPont Analysis',
    chapter: 3,
    formula: 'ROE = (Net Income / Sales) × (Sales / Total Assets) × (Total Assets / Total Equity)',
    latex: '\\text{ROE} = \\frac{\\text{NI}}{\\text{Sales}} \\times \\frac{\\text{Sales}}{\\text{TA}} \\times \\frac{\\text{TA}}{\\text{TE}}',
    variables: [
      { symbol: 'Net Income', name: 'Net Income', description: 'Profit' },
      { symbol: 'Sales', name: 'Sales', description: 'Revenue' },
      { symbol: 'Total Assets', name: 'Total Assets', description: 'All assets' },
      { symbol: 'Total Equity', name: 'Total Equity', description: 'Shareholders\' equity' }
    ],
    description: 'ROE = Profit Margin × Total Asset Turnover × Equity Multiplier',
    relatedFormulas: ['ch3-profit-margin', 'ch3-tat', 'ch3-equity-multiplier'],
    difficulty: 'advanced',
    tags: ['ratio-analysis', 'dupont', 'profitability']
  },
  {
    id: 'ch3-pe-ratio',
    name: 'Price-Earnings Ratio',
    category: 'Market Value Ratios',
    chapter: 3,
    formula: 'P/E = Price per Share / Earnings per Share',
    latex: '\\text{P/E} = \\frac{\\text{Price per Share}}{\\text{EPS}}',
    variables: [
      { symbol: 'Price per Share', name: 'Market Price', description: 'Current stock price' },
      { symbol: 'EPS', name: 'Earnings per Share', description: 'Net Income / Shares Outstanding' }
    ],
    description: 'Valuation multiple showing how much investors pay per dollar of earnings',
    difficulty: 'basic',
    tags: ['ratio-analysis', 'market-value', 'valuation']
  },
  {
    id: 'ch3-market-book',
    name: 'Market-to-Book Ratio',
    category: 'Market Value Ratios',
    chapter: 3,
    formula: 'M/B = Market Value per Share / Book Value per Share',
    latex: '\\text{M/B} = \\frac{\\text{Market Value per Share}}{\\text{Book Value per Share}}',
    variables: [
      { symbol: 'Market Value per Share', name: 'Market Price', description: 'Current stock price' },
      { symbol: 'Book Value per Share', name: 'Book Value', description: 'Total Equity / Shares Outstanding' }
    ],
    description: 'Compares market value to accounting book value',
    difficulty: 'basic',
    tags: ['ratio-analysis', 'market-value', 'valuation']
  },
  {
    id: 'ch3-efn',
    name: 'External Financing Needed',
    category: 'Financial Planning',
    chapter: 3,
    formula: 'EFN = (Assets / Sales) × ΔSales - (Liabilities / Sales) × ΔSales - PM × Projected Sales × (1 - d)',
    latex: '\\text{EFN} = \\frac{\\text{A}}{\\text{S}} \\times \\Delta S - \\frac{\\text{L}}{\\text{S}} \\times \\Delta S - \\text{PM} \\times S_1 \\times (1-d)',
    variables: [
      { symbol: 'A', name: 'Assets', description: 'Total assets' },
      { symbol: 'S', name: 'Sales', description: 'Current sales' },
      { symbol: 'ΔS', name: 'Change in Sales', description: 'Projected increase in sales' },
      { symbol: 'L', name: 'Spontaneous Liabilities', description: 'Liabilities that vary with sales (e.g., A/P)' },
      { symbol: 'PM', name: 'Profit Margin', description: 'Net Income / Sales' },
      { symbol: 'd', name: 'Payout Ratio', description: 'Dividends / Net Income' }
    ],
    description: 'Calculates additional external financing needed to support sales growth',
    difficulty: 'advanced',
    tags: ['financial-planning', 'growth', 'financing']
  },
  {
    id: 'ch3-internal-growth',
    name: 'Internal Growth Rate',
    category: 'Growth Analysis',
    chapter: 3,
    formula: 'IGR = (ROA × b) / (1 - ROA × b)',
    latex: '\\text{IGR} = \\frac{\\text{ROA} \\times b}{1 - \\text{ROA} \\times b}',
    variables: [
      { symbol: 'ROA', name: 'Return on Assets', description: 'Net Income / Total Assets' },
      { symbol: 'b', name: 'Retention Ratio', description: '1 - Payout Ratio = (NI - Div) / NI' }
    ],
    description: 'Maximum growth rate with no external financing of any kind',
    difficulty: 'advanced',
    tags: ['growth', 'financial-planning', 'internal-financing']
  },
  {
    id: 'ch3-sustainable-growth',
    name: 'Sustainable Growth Rate',
    category: 'Growth Analysis',
    chapter: 3,
    formula: 'SGR = (ROE × b) / (1 - ROE × b)',
    latex: '\\text{SGR} = \\frac{\\text{ROE} \\times b}{1 - \\text{ROE} \\times b}',
    variables: [
      { symbol: 'ROE', name: 'Return on Equity', description: 'Net Income / Total Equity' },
      { symbol: 'b', name: 'Retention Ratio', description: 'Proportion of earnings retained' }
    ],
    description: 'Maximum growth rate while maintaining constant debt-equity ratio',
    example: {
      problem: 'ROE = 26.4%, Retention Ratio = 66.7%. Calculate SGR.',
      solution: 'SGR = (0.264 × 0.667) / (1 - 0.264 × 0.667) = 0.2136 = 21.36%',
      values: { ROE: 0.264, b: 0.667, SGR: 0.2136 }
    },
    difficulty: 'advanced',
    tags: ['growth', 'financial-planning', 'sustainable']
  },

  // Chapter 4: Discounted Cash Flow Valuation
  {
    id: 'ch4-fv-single',
    name: 'Future Value (Single Period)',
    category: 'Time Value of Money',
    chapter: 4,
    formula: 'FV = PV × (1 + r)',
    latex: '\\text{FV} = \\text{PV} \\times (1 + r)',
    variables: [
      { symbol: 'FV', name: 'Future Value', description: 'Value at end of period' },
      { symbol: 'PV', name: 'Present Value', description: 'Value today' },
      { symbol: 'r', name: 'Interest Rate', description: 'Periodic interest rate' }
    ],
    description: 'Basic formula for future value of a single cash flow',
    difficulty: 'basic',
    tags: ['time-value', 'future-value', 'single-period']
  },
  {
    id: 'ch4-pv-single',
    name: 'Present Value (Single Period)',
    category: 'Time Value of Money',
    chapter: 4,
    formula: 'PV = FV / (1 + r)',
    latex: '\\text{PV} = \\frac{\\text{FV}}{1 + r}',
    variables: [
      { symbol: 'PV', name: 'Present Value', description: 'Value today' },
      { symbol: 'FV', name: 'Future Value', description: 'Value in one period' },
      { symbol: 'r', name: 'Interest Rate', description: 'Periodic interest rate' }
    ],
    description: 'Basic formula for present value of a single cash flow',
    difficulty: 'basic',
    tags: ['time-value', 'present-value', 'discounting']
  },
  {
    id: 'ch4-fv-multi',
    name: 'Future Value (Multiple Periods)',
    category: 'Time Value of Money',
    chapter: 4,
    formula: 'FV = C₀ × (1 + r)^t',
    latex: '\\text{FV} = C_0 \\times (1 + r)^t',
    variables: [
      { symbol: 'C₀', name: 'Cash Flow at Time 0', description: 'Initial investment' },
      { symbol: 'r', name: 'Interest Rate', description: 'Periodic interest rate' },
      { symbol: 't', name: 'Number of Periods', description: 'Time periods' }
    ],
    description: 'Compound interest formula for multiple periods',
    difficulty: 'basic',
    tags: ['time-value', 'future-value', 'compounding']
  },
  {
    id: 'ch4-pv-multi',
    name: 'Present Value (Multiple Periods)',
    category: 'Time Value of Money',
    chapter: 4,
    formula: 'PV = Cₜ / (1 + r)^t',
    latex: '\\text{PV} = \\frac{C_t}{(1 + r)^t}',
    variables: [
      { symbol: 'Cₜ', name: 'Cash Flow at Time t', description: 'Future cash flow' },
      { symbol: 'r', name: 'Discount Rate', description: 'Required rate of return' },
      { symbol: 't', name: 'Number of Periods', description: 'Time periods' }
    ],
    description: 'Present value with multiple period discounting',
    example: {
      problem: 'How much to invest today at 15% to have $20,000 in 5 years?',
      solution: 'PV = $20,000 / (1.15)^5 = $9,943.53',
      values: { FV: 20000, r: 0.15, t: 5, PV: 9943.53 }
    },
    difficulty: 'basic',
    tags: ['time-value', 'present-value', 'discounting']
  },
  {
    id: 'ch4-npv',
    name: 'Net Present Value',
    category: 'Time Value of Money',
    chapter: 4,
    formula: 'NPV = -Cost + PV(Future Cash Flows)',
    latex: '\\text{NPV} = -\\text{Cost} + \\sum_{t=1}^{T} \\frac{C_t}{(1+r)^t}',
    variables: [
      { symbol: 'Cost', name: 'Initial Cost', description: 'Initial investment (negative cash flow)' },
      { symbol: 'Cₜ', name: 'Cash Flow at Time t', description: 'Future cash inflows' },
      { symbol: 'r', name: 'Discount Rate', description: 'Required rate of return' }
    ],
    description: 'Present value of cash flows minus initial cost. Accept if NPV > 0.',
    difficulty: 'intermediate',
    tags: ['npv', 'capital-budgeting', 'valuation']
  },
  {
    id: 'ch4-ear',
    name: 'Effective Annual Rate',
    category: 'Interest Rates',
    chapter: 4,
    formula: 'EAR = (1 + APR/m)^m - 1',
    latex: '\\text{EAR} = \\left(1 + \\frac{\\text{APR}}{m}\\right)^m - 1',
    variables: [
      { symbol: 'EAR', name: 'Effective Annual Rate', description: 'True annual return accounting for compounding' },
      { symbol: 'APR', name: 'Annual Percentage Rate', description: 'Stated annual rate' },
      { symbol: 'm', name: 'Compounding Periods', description: 'Number of times interest compounds per year' }
    ],
    description: 'Converts stated APR to effective annual rate with compounding',
    example: {
      problem: '18% APR compounded monthly. Find EAR.',
      solution: 'EAR = (1 + 0.18/12)^12 - 1 = (1.015)^12 - 1 = 0.1956 = 19.56%',
      values: { APR: 0.18, m: 12, EAR: 0.1956 }
    },
    difficulty: 'intermediate',
    tags: ['interest-rates', 'compounding', 'ear']
  },
  {
    id: 'ch4-perpetuity',
    name: 'Perpetuity',
    category: 'Annuities',
    chapter: 4,
    formula: 'PV = C / r',
    latex: '\\text{PV} = \\frac{C}{r}',
    variables: [
      { symbol: 'C', name: 'Cash Flow', description: 'Constant periodic payment' },
      { symbol: 'r', name: 'Discount Rate', description: 'Required rate of return' }
    ],
    description: 'Present value of infinite constant cash flows',
    example: {
      problem: 'British consol pays £15 forever at 10% discount rate. What is PV?',
      solution: 'PV = £15 / 0.10 = £150',
      values: { C: 15, r: 0.10, PV: 150 }
    },
    difficulty: 'intermediate',
    tags: ['perpetuity', 'annuities', 'valuation']
  },
  {
    id: 'ch4-growing-perpetuity',
    name: 'Growing Perpetuity',
    category: 'Annuities',
    chapter: 4,
    formula: 'PV = C / (r - g)',
    latex: '\\text{PV} = \\frac{C}{r - g}',
    variables: [
      { symbol: 'C', name: 'Next Cash Flow', description: 'Cash flow in next period' },
      { symbol: 'r', name: 'Discount Rate', description: 'Required rate of return' },
      { symbol: 'g', name: 'Growth Rate', description: 'Constant growth rate (g < r)' }
    ],
    description: 'Present value of infinite cash flows growing at constant rate',
    example: {
      problem: 'Next dividend = $1.30, g = 5%, r = 10%. What is PV?',
      solution: 'PV = $1.30 / (0.10 - 0.05) = $1.30 / 0.05 = $26.00',
      values: { C: 1.30, r: 0.10, g: 0.05, PV: 26.00 }
    },
    difficulty: 'intermediate',
    tags: ['perpetuity', 'growth', 'valuation']
  },
  {
    id: 'ch4-annuity',
    name: 'Ordinary Annuity',
    category: 'Annuities',
    chapter: 4,
    formula: 'PV = C × [(1 - 1/(1+r)^t) / r]',
    latex: '\\text{PV} = C \\times \\left[\\frac{1 - \\frac{1}{(1+r)^t}}{r}\\right]',
    variables: [
      { symbol: 'C', name: 'Cash Flow', description: 'Constant periodic payment' },
      { symbol: 'r', name: 'Discount Rate', description: 'Periodic rate' },
      { symbol: 't', name: 'Number of Periods', description: 'Total payments' }
    ],
    description: 'Present value of fixed number of constant cash flows',
    difficulty: 'intermediate',
    tags: ['annuity', 'time-value', 'valuation']
  },
  {
    id: 'ch4-growing-annuity',
    name: 'Growing Annuity',
    category: 'Annuities',
    chapter: 4,
    formula: 'PV = C × [(1 - (1+g)^t/(1+r)^t) / (r - g)]',
    latex: '\\text{PV} = C \\times \\left[\\frac{1 - \\frac{(1+g)^t}{(1+r)^t}}{r-g}\\right]',
    variables: [
      { symbol: 'C', name: 'First Cash Flow', description: 'Initial payment' },
      { symbol: 'r', name: 'Discount Rate', description: 'Required return' },
      { symbol: 'g', name: 'Growth Rate', description: 'Constant growth rate' },
      { symbol: 't', name: 'Number of Periods', description: 'Total payments' }
    ],
    description: 'Present value of cash flows growing at constant rate for fixed periods',
    difficulty: 'advanced',
    tags: ['annuity', 'growth', 'valuation']
  },

  // Chapter 5: Bond Valuation
  {
    id: 'ch5-bond-price',
    name: 'Bond Price',
    category: 'Bond Valuation',
    chapter: 5,
    formula: 'P = C × [(1 - 1/(1+r)^t) / r] + F / (1+r)^t',
    latex: '\\text{P} = C \\times \\left[\\frac{1 - \\frac{1}{(1+r)^t}}{r}\\right] + \\frac{F}{(1+r)^t}',
    variables: [
      { symbol: 'P', name: 'Bond Price', description: 'Current market price' },
      { symbol: 'C', name: 'Coupon Payment', description: 'Periodic interest payment' },
      { symbol: 'r', name: 'Yield to Maturity', description: 'Market interest rate / required return' },
      { symbol: 't', name: 'Periods to Maturity', description: 'Number of periods until bond matures' },
      { symbol: 'F', name: 'Face Value', description: 'Par value paid at maturity (usually $1,000)' }
    ],
    description: 'PV of coupon payments (annuity) + PV of face value',
    difficulty: 'intermediate',
    tags: ['bonds', 'valuation', 'fixed-income']
  },
  {
    id: 'ch5-current-yield',
    name: 'Current Yield',
    category: 'Bond Valuation',
    chapter: 5,
    formula: 'Current Yield = Annual Coupon / Price',
    latex: '\\text{Current Yield} = \\frac{\\text{Annual Coupon}}{\\text{Price}}',
    variables: [
      { symbol: 'Annual Coupon', name: 'Annual Coupon Payment', description: 'Total coupon paid per year' },
      { symbol: 'Price', name: 'Bond Price', description: 'Current market price' }
    ],
    description: 'Annual coupon income relative to bond price (excludes capital gains)',
    difficulty: 'basic',
    tags: ['bonds', 'yield', 'income']
  },
  {
    id: 'ch5-ytm-relation',
    name: 'YTM and Current Yield Relationship',
    category: 'Bond Valuation',
    chapter: 5,
    formula: 'YTM = Current Yield + Capital Gains Yield',
    latex: '\\text{YTM} = \\text{Current Yield} + \\text{Capital Gains Yield}',
    variables: [
      { symbol: 'YTM', name: 'Yield to Maturity', description: 'Total return if held to maturity' },
      { symbol: 'Current Yield', name: 'Current Yield', description: 'Coupon income yield' },
      { symbol: 'Capital Gains Yield', name: 'Capital Gains Yield', description: 'Price appreciation yield' }
    ],
    description: 'Decomposes total return into income and price change components',
    difficulty: 'intermediate',
    tags: ['bonds', 'yield', 'returns']
  },
  {
    id: 'ch5-fisher',
    name: 'Fisher Effect',
    category: 'Interest Rates',
    chapter: 5,
    formula: '(1 + R) = (1 + r) × (1 + h)',
    latex: '(1 + R) = (1 + r)(1 + h)',
    variables: [
      { symbol: 'R', name: 'Nominal Rate', description: 'Stated interest rate' },
      { symbol: 'r', name: 'Real Rate', description: 'Real rate of return (inflation-adjusted)' },
      { symbol: 'h', name: 'Inflation Rate', description: 'Expected inflation' }
    ],
    description: 'Relationship between nominal rates, real rates, and inflation. Approximation: R ≈ r + h',
    example: {
      problem: 'Real return = 10%, Expected inflation = 8%. Find nominal rate.',
      solution: 'R = (1.10)(1.08) - 1 = 0.188 = 18.8% (Approx: 10% + 8% = 18%)',
      values: { r: 0.10, h: 0.08, R: 0.188 }
    },
    difficulty: 'intermediate',
    tags: ['interest-rates', 'inflation', 'fisher-effect']
  },
  {
    id: 'ch5-zero-coupon',
    name: 'Zero-Coupon Bond Price',
    category: 'Bond Valuation',
    chapter: 5,
    formula: 'P = F / (1 + r)^t',
    latex: '\\text{P} = \\frac{F}{(1 + r)^t}',
    variables: [
      { symbol: 'P', name: 'Bond Price', description: 'Current market price' },
      { symbol: 'F', name: 'Face Value', description: 'Par value paid at maturity' },
      { symbol: 'r', name: 'Yield to Maturity', description: 'Required return' },
      { symbol: 't', name: 'Years to Maturity', description: 'Time until maturity' }
    ],
    description: 'Pure discount bond with no coupon payments',
    example: {
      problem: '30-year zero-coupon bond, $1,000 face, 6% YTM. Find price.',
      solution: 'P = $1,000 / (1.06)^30 = $174.11',
      values: { F: 1000, r: 0.06, t: 30, P: 174.11 }
    },
    difficulty: 'basic',
    tags: ['bonds', 'zero-coupon', 'valuation']
  },

  // Chapter 6: Stock Valuation
  {
    id: 'ch6-zero-growth',
    name: 'Zero Growth Stock (Perpetuity)',
    category: 'Stock Valuation',
    chapter: 6,
    formula: 'P₀ = Div / R',
    latex: 'P_0 = \\frac{\\text{Div}}{R}',
    variables: [
      { symbol: 'P₀', name: 'Stock Price Today', description: 'Current stock price' },
      { symbol: 'Div', name: 'Constant Dividend', description: 'Annual dividend (never changes)' },
      { symbol: 'R', name: 'Required Return', description: 'Discount rate' }
    ],
    description: 'Preferred stock or common stock with constant dividend forever',
    example: {
      problem: 'Dividend = $2.00, R = 8.5%. Find price.',
      solution: 'P = $2.00 / 0.085 = $23.53',
      values: { Div: 2.00, R: 0.085, P: 23.53 }
    },
    difficulty: 'basic',
    tags: ['stocks', 'dividend-discount-model', 'perpetuity']
  },
  {
    id: 'ch6-constant-growth',
    name: 'Constant Growth Model (Gordon Growth)',
    category: 'Stock Valuation',
    chapter: 6,
    formula: 'P₀ = D₁ / (R - g)',
    latex: 'P_0 = \\frac{D_1}{R - g}',
    variables: [
      { symbol: 'P₀', name: 'Stock Price Today', description: 'Current stock price' },
      { symbol: 'D₁', name: 'Next Dividend', description: 'Dividend expected in one year' },
      { symbol: 'R', name: 'Required Return', description: 'Discount rate' },
      { symbol: 'g', name: 'Growth Rate', description: 'Constant dividend growth rate (g < R)' }
    ],
    description: 'Most important stock valuation model for constant growth stocks',
    example: {
      problem: 'Last dividend = $0.50, g = 2%, R = 15%. Find price.',
      solution: 'D₁ = $0.50 × 1.02 = $0.51, P = $0.51 / (0.15 - 0.02) = $3.92',
      values: { D0: 0.50, g: 0.02, R: 0.15, D1: 0.51, P: 3.92 }
    },
    difficulty: 'intermediate',
    tags: ['stocks', 'dividend-discount-model', 'gordon-growth']
  },
  {
    id: 'ch6-required-return',
    name: 'Required Return from DDM',
    category: 'Stock Valuation',
    chapter: 6,
    formula: 'R = (D₁ / P₀) + g',
    latex: 'R = \\frac{D_1}{P_0} + g',
    variables: [
      { symbol: 'R', name: 'Required Return', description: 'Total expected return' },
      { symbol: 'D₁/P₀', name: 'Dividend Yield', description: 'Expected dividend yield' },
      { symbol: 'g', name: 'Capital Gains Yield', description: 'Expected growth rate' }
    ],
    description: 'Rearranged Gordon model: Total Return = Dividend Yield + Growth',
    example: {
      problem: 'Last div = $0.65, g = 4%, P = $11.25. Find R.',
      solution: 'D₁ = $0.65 × 1.04 = $0.676, R = ($0.676/$11.25) + 0.04 = 0.10 = 10%',
      values: { D0: 0.65, g: 0.04, P: 11.25, D1: 0.676, R: 0.10 }
    },
    difficulty: 'intermediate',
    tags: ['stocks', 'required-return', 'dividend-yield']
  },
  {
    id: 'ch6-growth-roe',
    name: 'Growth from ROE',
    category: 'Stock Valuation',
    chapter: 6,
    formula: 'g = Retention Ratio × ROE',
    latex: 'g = b \\times \\text{ROE}',
    variables: [
      { symbol: 'g', name: 'Growth Rate', description: 'Sustainable dividend growth rate' },
      { symbol: 'b', name: 'Retention Ratio', description: 'Proportion of earnings retained (1 - payout ratio)' },
      { symbol: 'ROE', name: 'Return on Equity', description: 'Return on retained earnings' }
    ],
    description: 'Growth rate derived from retention and profitability',
    example: {
      problem: 'Retention = 70%, ROE = 12%. Find growth rate.',
      solution: 'g = 0.70 × 0.12 = 0.084 = 8.4%',
      values: { b: 0.70, ROE: 0.12, g: 0.084 }
    },
    difficulty: 'intermediate',
    tags: ['stocks', 'growth', 'roe']
  },
  {
    id: 'ch6-pe-growth',
    name: 'P/E Ratio and Growth',
    category: 'Stock Valuation',
    chapter: 6,
    formula: 'P/E = (1 - b) / (R - g)',
    latex: '\\frac{P}{E} = \\frac{1 - b}{R - g}',
    variables: [
      { symbol: 'P/E', name: 'Price-Earnings Ratio', description: 'Valuation multiple' },
      { symbol: 'b', name: 'Retention Ratio', description: 'Proportion retained' },
      { symbol: 'R', name: 'Required Return', description: 'Discount rate' },
      { symbol: 'g', name: 'Growth Rate', description: 'Expected growth' }
    ],
    description: 'P/E positively related to growth, negatively to risk',
    difficulty: 'advanced',
    tags: ['stocks', 'pe-ratio', 'valuation']
  },
  {
    id: 'ch6-enterprise-value',
    name: 'Enterprise Value',
    category: 'Stock Valuation',
    chapter: 6,
    formula: 'EV = Market Cap + Debt - Cash',
    latex: '\\text{EV} = \\text{Market Cap} + \\text{Debt} - \\text{Cash}',
    variables: [
      { symbol: 'EV', name: 'Enterprise Value', description: 'Total firm value' },
      { symbol: 'Market Cap', name: 'Market Capitalization', description: 'Share price × shares outstanding' },
      { symbol: 'Debt', name: 'Market Value of Debt', description: 'Interest-bearing debt' },
      { symbol: 'Cash', name: 'Cash', description: 'Cash and equivalents' }
    ],
    description: 'Total value of the firm to all investors',
    difficulty: 'intermediate',
    tags: ['stocks', 'enterprise-value', 'valuation']
  }
];
